version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:4567"
    volumes:
      - .:/code
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: currency_data_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
