version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:4567"
    volumes:
      - .:/code
    links:
      - postgres
  postgres:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
